version: "3.5"
services:
  rchain-cloud:
    container_name: rchain-cloud
    build:
      context: .
      dockerfile: Dockerfile.rchaincloud
    ports:
      - "8080:3000"
    volumes:
      - rchain-cloud-data:/var/lib/rchain-cloud/data
    depends_on:
      - rchain-node
    networks:
      - rchain-local
  rchain-node:
    container_name: rchain-node
    image: rchain/rnode:latest
    networks:
      - rchain-local

networks:
  rchain-local:
    name: rchain-local

volumes:
  rchain-cloud-data:
